# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/agentic-notebook-exp',
                'doc_host': 'https://charlesvardeman.github.io',
                'git_url': 'https://github.com/charlesvardeman/agentic-notebook-exp',
                'lib_path': 'agentic_notebook_exp'},
  'syms': {'agentic_notebook_exp.core': {'agentic_notebook_exp.core.foo': ('core.html#foo', 'agentic_notebook_exp/core.py')}}}
